ALTER TABLE documents
    ADD COLUMN IF NOT EXISTS source_id TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS source_label TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS source_category TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS source_input_mode TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS source_original_ref TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS source_captured_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS source_content_type TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS source_adapter TEXT NOT NULL DEFAULT '';

ALTER TABLE revisions
    ADD COLUMN IF NOT EXISTS source_id TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS source_label TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS source_category TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS source_input_mode TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS source_original_ref TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS source_captured_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS source_content_type TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS source_adapter TEXT NOT NULL DEFAULT '';
